name: Build & deploy

on:
  push:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:

      matrix:
       include:
           - REACT_APP_DEBUG_MODE: 'true'
             
             

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
    

      
    - name: Create env file and build
      run: |
          touch .env
          echo REACT_APP_DEBUG_MODE=${{ matrix. REACT_APP_DEBUG_MODE }} >> .env
          echo "${REACT_APP_DEBUG_MODE}"
          export REACT_APP_DEBUG_MODE=${{ matrix.REACT_APP_DEBUG_MODE }}
          cat .env
          if [ '%$REACT_APP_DEBUG_MOD%' == 'true' ]; then
           echo "Debug mode is set to true"
          else
            echo "Debug mode is set to false"
          fi 

          
           
          printenv REACT_APP_DEBUG_MODE
    - name: Check Debug Mode
      run: |
      
        echo "REACT_APP_DEBUG_MODE value: $REACT_APP_DEBUG_MODE"
        if [ "$REACT_APP_DEBUG_MODE" == "REACT_APP_DEBUG_MODE=true" ]; then
          echo "Debug mode is set to true"
        else
          echo "Debug mode is set to false"
        fi 


    
